// react-native-mobile-app/app/(tabs)/checklist.tsx
import AsyncStorage from "@react-native-async-storage/async-storage";
import dayjs from "dayjs";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ActivityIndicator,
  FlatList,
  Pressable,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Bible } from "@mybiblelog/shared";
import { useLocale, useT } from "@/src/i18n/LocaleProvider";
import { useLogEntries } from "@/src/log-entries/LogEntriesProvider";
import { useTheme } from "@/src/theme/ThemeProvider";
import { useToast } from "@/src/toast/ToastProvider";

const CHECKLIST_CACHE_KEY = "chapterChecklist.v1";
const CHECKLIST_CACHE_MAX_AGE_MS = 60 * 60 * 1000;

type ChapterReport = {
  bookIndex: number;
  chapterIndex: number;
  complete: boolean;
};

type BookReport = {
  bookIndex: number;
  bookName: string;
  totalChapters: number;
  chaptersRead: number;
  percentage: number;
  complete: boolean;
  chapterReports: ChapterReport[];
};

function calcPercent(numerator: number, denominator: number): number {
  if (!denominator) return 0;
  return Math.floor((numerator / denominator) * 100);
}

function yieldToUI(): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, 0));
}

function initExpandedBooks(): Record<string, boolean> {
  const expanded: Record<string, boolean> = {};
  const bookCount = Bible.getBookCount();
  for (let i = 1; i <= bookCount; i++) expanded[String(i)] = false;
  return expanded;
}

export default function Checklist() {
  const t = useT();
  const { locale } = useLocale();
  const { colors } = useTheme();
  const { showToast } = useToast();
  const { state: logState, createEntry, deleteEntry } = useLogEntries();

  const [computeBusy, setComputeBusy] = useState(false);
  const [busyChapter, setBusyChapter] = useState<string | null>(null);
  const [expandedBooks, setExpandedBooks] = useState<Record<string, boolean>>(
    () => initExpandedBooks()
  );
  const [readChapters, setReadChapters] = useState<Record<string, boolean>>(
    {}
  );
  const [bookReports, setBookReports] = useState<BookReport[]>([]);

  const computeTokenRef = useRef(0);

  const logEntries = useMemo(() => {
    if (logState.status !== "ready") return [];
    return logState.entries;
  }, [logState]);

  const busy = Boolean(computeBusy || busyChapter);

  const loadCachedReports = useCallback(async () => {
    try {
      const raw = await AsyncStorage.getItem(CHECKLIST_CACHE_KEY);
      if (!raw) return;
      const parsed: unknown = JSON.parse(raw);
      if (!parsed || typeof parsed !== "object") return;
      const v = parsed as { ts?: unknown; data?: unknown };
      if (typeof v.ts !== "number") return;
      if (!Array.isArray(v.data)) return;
      if (Date.now() - v.ts > CHECKLIST_CACHE_MAX_AGE_MS) return;
      setBookReports(v.data as BookReport[]);
    } catch {
      // ignore cache issues
    }
  }, []);

  const computeReadChapters = useCallback(async () => {
    const ranges = Bible.consolidateRanges(logEntries);
    const nextRead: Record<string, boolean> = {};
    const markRead = (bookIndex: number, chapterIndex: number) => {
      nextRead[`${bookIndex}.${chapterIndex}`] = true;
    };

    for (const range of ranges) {
      const { book, chapter: startChapter, verse: startVerse } =
        Bible.parseVerseId(range.startVerseId);
      const { chapter: endChapter, verse: endVerse } = Bible.parseVerseId(
        range.endVerseId
      );

      if (startVerse === 1) {
        if (
          endChapter > startChapter ||
          Bible.getChapterVerseCount(book, startChapter) === endVerse
        ) {
          markRead(book, startChapter);
        }
      }
      if (
        endChapter > startChapter &&
        Bible.getChapterVerseCount(book, endChapter) === endVerse
      ) {
        markRead(book, endChapter);
      }
      if (endChapter > startChapter + 1) {
        for (let c = startChapter + 1; c < endChapter; c++) {
          markRead(book, c);
        }
      }

      await yieldToUI();
    }

    return nextRead;
  }, [logEntries]);

  const computeBookReports = useCallback(
    async (token: number) => {
      if (logState.status !== "ready") return;
      setComputeBusy(true);

      // Give a quick visual response while we compute.
      void loadCachedReports();

      const nextRead = await computeReadChapters();
      if (computeTokenRef.current !== token) return;
      setReadChapters(nextRead);

      const reports: BookReport[] = [];
      for (let bookIndex = 1, l = Bible.getBookCount(); bookIndex <= l; bookIndex++) {
        const bookName = Bible.getBookName(bookIndex, locale);
        const totalChapters = Bible.getBookChapterCount(bookIndex);
        const chapterReports: ChapterReport[] = [];
        let chaptersRead = 0;

        for (let chapterIndex = 1; chapterIndex <= totalChapters; chapterIndex++) {
          const complete = nextRead[`${bookIndex}.${chapterIndex}`] === true;
          if (complete) chaptersRead++;
          chapterReports.push({ bookIndex, chapterIndex, complete });
        }

        const percentage = calcPercent(chaptersRead, totalChapters);
        reports.push({
          bookIndex,
          bookName,
          totalChapters,
          chaptersRead,
          percentage,
          complete: percentage === 100,
          chapterReports,
        });

        await yieldToUI();
        if (computeTokenRef.current !== token) return;
      }

      setBookReports(reports);
      setComputeBusy(false);

      try {
        await AsyncStorage.setItem(
          CHECKLIST_CACHE_KEY,
          JSON.stringify({ ts: Date.now(), data: reports })
        );
      } catch {
        // ignore cache write issues
      }
    },
    [computeReadChapters, locale, loadCachedReports, logState.status]
  );

  useEffect(() => {
    // Preload cache so first paint has something to show.
    void loadCachedReports();
  }, [loadCachedReports]);

  useEffect(() => {
    computeTokenRef.current += 1;
    const token = computeTokenRef.current;
    void computeBookReports(token);
  }, [computeBookReports, locale, logEntries.length]);

  function toggleBook(bookIndex: number) {
    setExpandedBooks((prev) => ({
      ...prev,
      [String(bookIndex)]: !prev[String(bookIndex)],
    }));
  }

  async function toggleChapter(bookIndex: number, chapterIndex: number) {
    if (busyChapter) return;
    if (logState.status !== "ready") return;

    const key = `${bookIndex}.${chapterIndex}`;
    setBusyChapter(key);

    const date = dayjs().format("YYYY-MM-DD");
    const startVerseId = Bible.makeVerseId(bookIndex, chapterIndex, 1);
    const endVerseId = Bible.makeVerseId(
      bookIndex,
      chapterIndex,
      Bible.getChapterVerseCount(bookIndex, chapterIndex)
    );

    const isComplete = readChapters[key] === true;
    try {
      if (isComplete) {
        const matching = logEntries.find(
          (e) =>
            e.date === date &&
            e.startVerseId === startVerseId &&
            e.endVerseId === endVerseId
        );

        if (matching?.clientId) {
          await deleteEntry(matching.clientId);
        } else {
          showToast({ type: "info", message: t("logged_before_today") });
        }
      } else {
        await createEntry({ date, startVerseId, endVerseId });
      }
    } catch {
      showToast({
        type: "error",
        message: t(isComplete ? "unable_to_mark_incomplete" : "unable_to_mark_complete"),
      });
    } finally {
      setBusyChapter(null);
    }
  }

  const completeColor = colors.success;

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={styles.header}>
        <Text style={[styles.title, { color: colors.text }]}>{t("chapter_checklist")}</Text>
        {busy && <ActivityIndicator color={colors.primary} />}
      </View>

      {bookReports.length === 0 ? (
        <View style={[styles.loadingCard, { backgroundColor: colors.surface }]}>
          <Text style={[styles.loadingText, { color: colors.mutedText }]}>
            {t("loading")}
          </Text>
        </View>
      ) : (
        <FlatList
          data={bookReports}
          keyExtractor={(b) => String(b.bookIndex)}
          contentContainerStyle={styles.listContent}
          renderItem={({ item }) => {
            const isExpanded = expandedBooks[String(item.bookIndex)] === true;
            return (
              <View
                style={[
                  styles.bookCard,
                  { backgroundColor: colors.surface, borderColor: colors.border },
                ]}
              >
                <Pressable
                  onPress={() => toggleBook(item.bookIndex)}
                  style={styles.bookHeader}
                >
                  <View style={styles.bookHeaderLeft}>
                    <Ionicons
                      name={item.complete ? "checkmark-circle" : "ellipse-outline"}
                      size={18}
                      color={item.complete ? completeColor : colors.border}
                      style={{ marginRight: 10 }}
                    />
                    <Text style={[styles.bookName, { color: colors.text }]}>
                      {item.bookName}
                    </Text>
                  </View>

                  <View style={styles.bookHeaderRight}>
                    <Text style={[styles.bookFraction, { color: colors.mutedText }]}>
                      {item.chaptersRead} / {item.totalChapters}
                    </Text>
                    <Ionicons
                      name="chevron-down"
                      size={18}
                      color={colors.mutedText}
                      style={isExpanded && { transform: [{ rotate: "180deg" }] }}
                    />
                  </View>
                </Pressable>

                <View style={[styles.progressTrack, { backgroundColor: colors.surfaceAlt }]}>
                  <View
                    style={[
                      styles.progressFill,
                      { width: `${item.percentage}%`, backgroundColor: completeColor },
                    ]}
                  />
                </View>

                {isExpanded && (
                  <View style={styles.chaptersWrap}>
                    {item.chapterReports.map((c) => {
                      const chapterKey = `${c.bookIndex}.${c.chapterIndex}`;
                      const isBusy = busyChapter === chapterKey;
                      const isCompleteChapter = c.complete;
                      return (
                        <Pressable
                          key={chapterKey}
                          onPress={() => void toggleChapter(c.bookIndex, c.chapterIndex)}
                          style={[
                            styles.chapterCard,
                            { backgroundColor: colors.surface, borderColor: colors.border },
                          ]}
                        >
                          <Text style={[styles.chapterNumber, { color: colors.text }]}>
                            {c.chapterIndex}
                          </Text>
                          <View style={styles.chapterIndicator}>
                            {isBusy ? (
                              <ActivityIndicator
                                size="small"
                                color={isCompleteChapter ? colors.mutedText : completeColor}
                              />
                            ) : (
                              <Ionicons
                                name={isCompleteChapter ? "checkmark-circle" : "ellipse-outline"}
                                size={18}
                                color={isCompleteChapter ? completeColor : colors.border}
                              />
                            )}
                          </View>
                        </Pressable>
                      );
                    })}
                  </View>
                )}
              </View>
            );
          }}
          ItemSeparatorComponent={() => <View style={{ height: 12 }} />}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
  },
  listContent: {
    paddingBottom: 24,
  },
  loadingCard: {
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,0,0,0.10)",
  },
  loadingText: {
    fontSize: 14,
    fontWeight: "800",
  },
  bookCard: {
    borderRadius: 14,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
  },
  bookHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
  },
  bookHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 1,
    paddingRight: 10,
  },
  bookHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  bookName: {
    fontSize: 15,
    fontWeight: "900",
    flexShrink: 1,
  },
  bookFraction: {
    fontSize: 13,
    fontWeight: "800",
  },
  progressTrack: {
    height: 8,
    borderRadius: 6,
    overflow: "hidden",
    marginTop: 10,
  },
  progressFill: {
    height: "100%",
    borderRadius: 6,
  },
  chaptersWrap: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  chapterCard: {
    width: 54,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: "center",
    justifyContent: "center",
  },
  chapterNumber: {
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 6,
  },
  chapterIndicator: {
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
});

// nuxt/pages/checklist.vue
<template>
  <div class="content-column">
    <busy-bar :busy="busy" />
    <header class="page-header">
      <h2 class="title">
        {{ $t('chapter_checklist') }}
        <info-link :to="localePath('/about/page-features--chapter-checklist')" />
      </h2>
    </header>
    <br>
    <div>
      <div v-if="!bookReports.length" class="loading-card">
        <strong>{{ $t('loading') }}</strong>
      </div>
      <div v-for="bookReport in bookReports" :key="bookReport.bookIndex" class="book-card">
        <div class="book-card--header">
          <div>
            <check-mark-icon width="100%" height="100%" :fill="bookReport.complete ? '#0c0' : 'transparent'" />
          </div>
          <div class="book-card--book-name">
            {{ bookReport.bookName }}
          </div>
          <div class="book-card--completion-fraction">
            {{ bookReport.chaptersRead }} / {{ bookReport.totalChapters }}
          </div>
          <div class="book-card--chapter-toggle" :class="{ flipped: expandedBooks[bookReport.bookIndex] }" @click="toggleBook(bookReport.bookIndex)">
            <caret-down-icon width="2rem" height="2rem" fill="#ccc" />
          </div>
          <div class="book-card--completion-bar">
            <completion-bar :percentage="bookReport.percentage" foreground-color="#0c0" />
          </div>
        </div>
        <div v-if="expandedBooks[bookReport.bookIndex]" class="book-card--chapters">
          <div v-for="chapterReport in bookReport.chapterReports" :key="chapterReport.chapterIndex" class="chapter-card" @click="toggleChapter(chapterReport.bookIndex, chapterReport.chapterIndex)">
            <div class="chapter-card--chapter-number">
              {{ chapterReport.chapterIndex }}
            </div>
            <div class="chapter-card--completion-indicator">
              <spinner-icon v-if="busyChapter === `${bookReport.bookIndex}.${chapterReport.chapterIndex}`" width="100%" height="100%" :fill="chapterReport.complete ? '#ddd' : '#0c0'" />
              <check-mark-icon v-else width="100%" height="100%" :fill="chapterReport.complete ? '#0c0' : 'transparent'" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import * as dayjs from 'dayjs';
import { Bible, BrowserCache } from '@mybiblelog/shared';
import BusyBar from '@/components/BusyBar';
import CompletionBar from '@/components/CompletionBar';
import CheckMarkIcon from '@/components/svg/CheckMarkIcon';
import CaretDownIcon from '@/components/svg/CaretDownIcon';
import SpinnerIcon from '@/components/svg/SpinnerIcon';
import InfoLink from '@/components/InfoLink';
import { useToastStore } from '~/stores/toast';
import { useLogEntriesStore } from '~/stores/log-entries';
const CHAPTER_CHECKLIST_CACHE_KEY = 'chapterChecklist';
const CHAPTER_CHECKLIST_CACHE_MINUTES = 60;

const calcPercent = (numerator, denominator) => {
  return Math.floor(numerator / denominator * 100);
};

export default {
  components: {
    BusyBar,
    CompletionBar,
    CheckMarkIcon,
    CaretDownIcon,
    SpinnerIcon,
    InfoLink,
  },
  middleware: ['auth'],
  data() {
    const expandedBooks = {};
    const bookCount = Bible.getBookCount();
    for (let i = 1; i <= bookCount; i++) {
      expandedBooks[i] = false;
    }
    return {
      computeBusy: false,
      busyChapter: null,
      expandedBooks,
      readChapters: {},
      bookReports: [],
    };
  },
  head() {
    return {
      title: this.$t('chapter_checklist'),
    };
  },
  computed: {
    logEntriesStore() {
      return useLogEntriesStore();
    },
    logEntries() {
      return this.logEntriesStore.currentLogEntries;
    },
    busy() {
      return Boolean(this.busyChapter || this.computeBusy);
    },
  },
  mounted() {
    setTimeout(this.getBookReports);
  },
  methods: {
    async getReadChapters() {
      const ranges = Bible.consolidateRanges(this.logEntries);
      const readChapters = {}; // { [`${bookIndex}.${chapterIndex}`]: boolean }
      function markRead(bookIndex, chapterIndex) { readChapters[`${bookIndex}.${chapterIndex}`] = true; }

      for (const range of ranges) {
        const { book, chapter: startChapter, verse: startVerse } = Bible.parseVerseId(range.startVerseId);
        const { chapter: endChapter, verse: endVerse } = Bible.parseVerseId(range.endVerseId);

        if (startVerse === 1) {
          if (endChapter > startChapter || Bible.getChapterVerseCount(book, startChapter) === endVerse) {
            markRead(book, startChapter);
          }
        }
        if (endChapter > startChapter && Bible.getChapterVerseCount(book, endChapter) === endVerse) {
          markRead(book, endChapter);
        }
        if (endChapter > startChapter + 1) {
          for (let c = startChapter + 1; c < endChapter; c++) {
            markRead(book, c);
          }
        }

        // Give up the event loop to let other things happen
        await new Promise(resolve => setImmediate(resolve));
      }
      this.readChapters = readChapters;
    },
    getBookReport(bookIndex, readChapters) {
      const bookName = Bible.getBookName(bookIndex, this.$i18n.locale);
      const totalChapters = Bible.getBookChapterCount(bookIndex);
      const chapterReports = [];
      let chaptersRead = 0;
      for (let chapterIndex = 1, l = totalChapters; chapterIndex <= l; chapterIndex++) {
        const totalVerses = Bible.getChapterVerseCount(bookIndex, chapterIndex);
        const versesRead = Bible.countUniqueBookChapterRangeVerses(bookIndex, chapterIndex, this.logEntries);
        const complete = readChapters[`${bookIndex}.${chapterIndex}`];
        if (complete) {
          chaptersRead++;
        }
        chapterReports.push({ totalVerses, versesRead, bookIndex, chapterIndex, complete });
      }
      const percentage = calcPercent(chaptersRead, totalChapters);
      const complete = percentage === 100;
      return { bookIndex, bookName, totalChapters, chaptersRead, percentage, complete, chapterReports };
    },
    async getBookReports() {
      this.computeBusy = true;

      // Check for cached data to give an immediate visual response
      const cachedBookReports = BrowserCache.get(CHAPTER_CHECKLIST_CACHE_KEY);
      if (cachedBookReports) {
        this.bookReports = cachedBookReports;
      }

      await this.getReadChapters();
      const bookReports = [];
      for (let i = 1, l = Bible.getBookCount(); i <= l; i++) {
        bookReports.push(this.getBookReport(i, this.readChapters));

        // Give up the event loop to let other things happen
        await new Promise(resolve => setImmediate(resolve));
      }

      // Cache book reports
      BrowserCache.set(CHAPTER_CHECKLIST_CACHE_KEY, bookReports, CHAPTER_CHECKLIST_CACHE_MINUTES);

      this.bookReports = bookReports;
      this.computeBusy = false;
    },
    toggleBook(bookIndex) {
      if (this.expandedBooks[bookIndex]) {
        this.expandedBooks[bookIndex] = false;
      }
      else {
        this.expandedBooks[bookIndex] = true;
      }
    },
    async toggleChapter(bookIndex, chapterIndex) {
      if (this.busyChapter) {
        return;
      }
      const toastStore = useToastStore();
      this.busyChapter = `${bookIndex}.${chapterIndex}`;

      const date = dayjs().format('YYYY-MM-DD');
      const startVerseId = Bible.makeVerseId(bookIndex, chapterIndex, 1);
      const endVerseId = Bible.makeVerseId(bookIndex, chapterIndex, Bible.getChapterVerseCount(bookIndex, chapterIndex));

      const isComplete = this.readChapters[`${bookIndex}.${chapterIndex}`] === true;
      if (isComplete) {
        const matchingLogEntry = this.logEntries.find(logEntry => (
          logEntry.date === date &&
          logEntry.startVerseId === startVerseId &&
          logEntry.endVerseId === endVerseId
        ));
        if (matchingLogEntry) {
          const success = await this.logEntriesStore.deleteLogEntry(matchingLogEntry.id);
          if (success) {
            await this.getBookReports();
          }
          else {
            toastStore.add({
              type: 'error',
              text: this.$t('unable_to_mark_incomplete'),
            });
          }
        }
        else {
          toastStore.add({
            type: 'info',
            text: this.$t('logged_before_today'),
          });
        }
      }
      else {
        const newLogEntry = { date, startVerseId, endVerseId };
        const createdEntry = await this.logEntriesStore.createLogEntry(newLogEntry);
        if (createdEntry) {
          await this.getBookReports();
        }
        else {
          toastStore.add({
            type: 'error',
            text: this.$t('unable_to_mark_complete'),
          });
        }
      }
      this.busyChapter = null;
    },
  },
};
</script>

<style lang="scss" scoped>
.loading-card {
  padding: 1rem 2rem;
  border-radius: 0.25rem;
  box-shadow: 0 1px 7px #999;
  margin: 0.5rem 0;
}

.book-card {
  user-select: none;
}

.book-card--header {
  display: grid;
  grid-template-columns: 2rem 1fr 1fr 2rem;
  grid-template-rows: auto auto;

  padding: 0.5rem;
  border-radius: 0.25rem;
  box-shadow: 0 1px 7px #999;
  margin: 0.5rem 0;

  font-size: 0.8rem;
  font-weight: bold;
}

.book-card--completion-indicator {
  grid-area: 1 / 1 / 3 / 2;
  width: 1.5rem;
  margin-right: 0.5rem;
  display: flex;
}

.book-card--book-name {
  grid-area: 1 / 2 / 2 / 3;
}

.book-card--completion-fraction {
  grid-area: 1 / 3 / 2 / 4;
  text-align: right;
}

.book-card--completion-bar {
  grid-area: 2 / 2 / 3 / 4;
}

.book-card--chapter-toggle {
  grid-area: 1 / 4 / 3 / 5;
  display: flex;
  cursor: pointer;
  &.flipped {
    transform: rotate(180deg);
  }
}

.book-card--chapters {
  display: grid;
  gap: 0.5rem;
  grid-template-columns: repeat(5, 1fr);
  @media screen and (min-width: 769px) {
    grid-template-columns: repeat(6, 1fr);
  }
  @media screen and (min-width: 1024px) {
    grid-template-columns: repeat(8, 1fr);
  }
  @media screen and (min-width: 1216px) {
    grid-template-columns: repeat(10, 1fr);
  }
  @media screen and (min-width: 1408px) {
    grid-template-columns: repeat(12, 1fr);
  }

  // margin: -5px;
}

.chapter-card {
  // margin: 0.5rem;
  padding: 0.5rem;
  border-radius: 0.25rem;
  box-shadow: 0 1px 7px #999;

  flex-basis: calc(25% - 1rem);
  position: relative;

  cursor: pointer;

  transition: 0.1s;
  &:hover {
    transition: 0.2s;
    box-shadow: 0 1px 9px #333;
  }
}

.chapter-card--chapter-number {
  text-align: center;
  font-weight: bold;
}
</style>

<i18n locale="en" lang="json" src="@/locales/sfc/en/pages/checklist.json" />
<i18n locale="de" lang="json" src="@/locales/sfc/de/pages/checklist.json" />
<i18n locale="es" lang="json" src="@/locales/sfc/es/pages/checklist.json" />
<i18n locale="fr" lang="json" src="@/locales/sfc/fr/pages/checklist.json" />
<i18n locale="ko" lang="json" src="@/locales/sfc/ko/pages/checklist.json" />
<i18n locale="pt" lang="json" src="@/locales/sfc/pt/pages/checklist.json" />
<i18n locale="uk" lang="json" src="@/locales/sfc/uk/pages/checklist.json" />
